# Generated by Django 3.0.8 on 2020-07-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_autherregistration_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='autherregistration',
            name='profileimage',
            field=models.ImageField(default='ImageFeild', upload_to='images/'),
        ),
    ]
