# Generated by Django 3.0.8 on 2020-07-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_autherregistration_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autherregistration',
            name='profileimage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
